-- ═══════════════════════════════════════════════════════════════════════════
-- Account deletion: deletion_requests + deletion email templates
-- ═══════════════════════════════════════════════════════════════════════════
-- Run in Supabase → SQL Editor. Idempotent: safe to re-run.
--
-- REQUIRED BY supabase/functions/delete-account/index.ts and by the web-based
-- deletion request page. Run this BEFORE deploying the deletion functions, or
-- the confirm flow has nowhere to record its tokens.
--
-- WHY THIS EXISTS
-- Apple Guideline 5.1.1(v) requires account deletion to be initiated IN the
-- app, and Google Play additionally requires a web-based deletion request page
-- reachable without installing the app. Those are two different trust models:
--
--   • IN-APP (immediate): the caller holds a valid authenticated JWT, so the
--     account is already proven and deletion runs straight away. Nothing in
--     this file is involved — delete-account reads the target from the JWT's
--     own `sub` claim.
--   • WEB (confirm-by-email): the requester is anonymous. Anyone could type
--     anyone's address, so the request only becomes actionable after the owner
--     of the mailbox clicks a one-time link. `deletion_requests` is that
--     pending state.
--
-- THE RESPONSE MUST NOT REVEAL WHETHER AN EMAIL IS REGISTERED
-- user_id is nullable on purpose. A request for an address with no account
-- still gets a row (with user_id null and no email sent), so the web page can
-- return exactly the same "check your inbox" response either way. Branching the
-- response on whether the account exists would turn the page into an account
-- enumeration oracle.
--
-- TOKENS ARE GENERATED BY THE FUNCTION, NOT BY POSTGRES
-- `token` has no default. The Edge Function mints it with
-- crypto.getRandomValues() and stores the result here. Postgres' gen_random_uuid()
-- is fine as a surrogate key but a UUIDv4 is not a secret to hand out in a URL —
-- it carries version/variant bits and is generated where the value is also
-- logged. Single-use is enforced by `consumed_at`, expiry by `expires_at`.
--
-- The seeded `deletion_confirm` copy states that the link expires in 24 hours,
-- so the sender must write `expires_at = now() + interval '24 hours'`. Change
-- both together or the email will lie.

create extension if not exists pgcrypto;

-- ─── deletion_requests ───────────────────────────────────────────────────────

create table if not exists public.deletion_requests (
  id uuid primary key default gen_random_uuid(),
  -- The address the request was made for, recorded even when it matches no
  -- account (see the enumeration note above).
  email text not null,
  -- Null when no account matched at request time. Cascades so a deleted
  -- account never leaves a live token pointing at it.
  user_id uuid references auth.users(id) on delete cascade,
  -- Securely random, minted by the Edge Function. Unique so a replayed insert
  -- can never silently shadow an existing pending request.
  token text not null unique,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  -- Set the moment the token is redeemed. Non-null means spent: the confirm
  -- function must refuse it even if expires_at is still in the future.
  consumed_at timestamptz
);

comment on table public.deletion_requests is
  'Pending web-initiated account deletion requests. Service-role only: RLS is enabled with no policies, so every anon/authenticated client is denied.';
comment on column public.deletion_requests.user_id is
  'Null when the requested email matched no account. The row is still written so the web response cannot be used to enumerate registered addresses.';
comment on column public.deletion_requests.token is
  'Single-use confirmation secret, generated by the Edge Function with crypto.getRandomValues() (never by Postgres). Spent when consumed_at is set.';
comment on column public.deletion_requests.consumed_at is
  'Redemption timestamp. A non-null value permanently invalidates the token.';

-- Token lookup is the hot path (one read per confirmation click).
create index if not exists deletion_requests_token_idx
  on public.deletion_requests (token);

-- Supports both the "is there already a live request for this email" check and
-- the eventual cleanup of stale rows.
create index if not exists deletion_requests_pending_idx
  on public.deletion_requests (expires_at)
  where consumed_at is null;

create index if not exists deletion_requests_email_idx
  on public.deletion_requests (email, created_at desc);

-- ── Row level security ──────────────────────────────────────────────────────
-- Enabled with ZERO policies, and that is the entire access model: RLS with no
-- matching policy denies every operation to anon and authenticated, while the
-- service role bypasses RLS and is unaffected. Only the deletion Edge Functions
-- ever touch this table.
--
-- Do NOT add a policy here. A readable token is a deletable account: anyone who
-- could select a pending row could delete the account it points at, and anyone
-- who could insert one could forge a request. The drops below are defensive —
-- they remove any policy a previous experiment may have left behind, so
-- re-running this file always returns the table to "no policies".

alter table public.deletion_requests enable row level security;

drop policy if exists deletion_requests_select_own on public.deletion_requests;
drop policy if exists deletion_requests_insert_own on public.deletion_requests;
drop policy if exists deletion_requests_read on public.deletion_requests;

-- ═══════════════════════════════════════════════════════════════════════════
-- email_templates: allow the two account-deletion keys
-- ═══════════════════════════════════════════════════════════════════════════
-- template_key carries a CHECK constraint listing every permitted key, so a new
-- template cannot simply be inserted — the constraint has to be widened first.
--
-- The constraint's name is NOT assumed. It was created inline by
-- `check (template_key in (...))` inside a CREATE TABLE, so Postgres generated
-- the name, and it differs between environments that built the table at
-- different times (and from a re-run of this file). Look it up from the
-- catalog by what it constrains instead.

do $$
declare
  c record;
begin
  for c in
    select con.conname
    from pg_constraint con
    join pg_class rel on rel.oid = con.conrelid
    join pg_namespace nsp on nsp.oid = rel.relnamespace
    where nsp.nspname = 'public'
      and rel.relname = 'email_templates'
      -- 'c' is a CHECK constraint: this deliberately excludes the NOT NULL
      -- ('n' in PG17) and UNIQUE ('u') constraints on the same column.
      and con.contype = 'c'
      and pg_get_constraintdef(con.oid) ilike '%template_key%'
  loop
    execute format('alter table public.email_templates drop constraint %I;', c.conname);
    raise notice 'account_deletion.sql: dropped check constraint % on public.email_templates', c.conname;
  end loop;
end $$;

-- Recreated under a known, stable name. Because the loop above drops ANY check
-- constraint mentioning template_key — including this one — re-running the file
-- is safe.
alter table public.email_templates
  add constraint email_templates_template_key_check
  check (
    template_key in (
      'welcome',
      'verification',
      'deletion_warning',
      'cancellation_confirm',
      'deletion_confirm',
      'deletion_complete'
    )
  );

-- ── Seed the two deletion templates ─────────────────────────────────────────
-- ON CONFLICT DO NOTHING: never overwrites admin edits, safe to re-run.
--
-- The same copy is mirrored in FALLBACK_TEMPLATES in
-- src/services/emailTemplates.ts (same text and inline styles, pretty-printed
-- there), which is what ships in the binary when this table read fails. Edit
-- both or they drift.
--
-- NOTE on available_variables: this project's live column is TEXT holding a
-- human-readable hint like '{user_name}, {deletion_date}' — NOT the jsonb array
-- that supabase/email_templates.sql declares, and not a Postgres text[] either.
-- The two rows below follow the live convention so all six read alike. (The
-- app does not depend on it: normalizeVariables() in emailTemplates.ts only
-- accepts an array, so a text value yields [] and the hardcoded
-- FALLBACK_TEMPLATES list is used for every template, these included.)
--
-- NOTE on 'deletion_warning' vs these two: deletion_warning is about a cancelled
-- subscriber's DOCUMENTS being purged after the 30-day grace period. These two
-- are about the whole ACCOUNT going away. Different flows, different copy.

insert into public.email_templates (template_key, subject, body_html, available_variables)
values
  (
    'deletion_confirm',
    'Confirm your Compliance Co-Pilot account deletion',
    '<!doctype html><html><body style="font-family:-apple-system,system-ui,sans-serif;color:#1a1a2e;max-width:560px;margin:0 auto;padding:24px;"><h1 style="color:#A32D2D;margin-bottom:8px;">Confirm account deletion</h1><p>Hi {user_name},</p><p>We received a request to permanently delete your Compliance Co-Pilot account. Tap below to confirm.</p><div style="background:#FCEBEB;border-left:4px solid #A32D2D;padding:16px;border-radius:8px;margin:24px 0;"><p style="margin:0;"><strong>This permanently deletes your account and every compliance record in it</strong> — documents, hours logs, business trips, meeting minutes, mileage, businesses and properties.</p><p style="margin:8px 0 0;">It cannot be undone, and we cannot recover anything afterwards.</p></div><p><a href="{confirm_link}" style="display:inline-block;background:#A32D2D;color:#fff;text-decoration:none;padding:12px 18px;border-radius:8px;font-weight:700;">Confirm account deletion</a></p><p>For your security this link works once and expires 24 hours after it was sent.</p><p><strong>Didn''t request this?</strong> Ignore this email and nothing will happen. Your account stays exactly as it is.</p><p>Deleting your account does not cancel an active App Store or Google Play subscription — cancel that in the store to stop billing.</p><p style="color:#6b7280;font-size:12px;margin-top:32px;">Compliance Co-Pilot</p></body></html>',
    '{user_name}, {confirm_link}'
  ),
  (
    'deletion_complete',
    'Your Compliance Co-Pilot account has been deleted',
    '<!doctype html><html><body style="font-family:-apple-system,system-ui,sans-serif;color:#1a1a2e;max-width:560px;margin:0 auto;padding:24px;"><h1 style="color:#042C53;margin-bottom:8px;">Account deleted</h1><p>Hi {user_name},</p><p>Your Compliance Co-Pilot account has been permanently deleted, along with all of the data in it.</p><div style="background:#F5F7FA;border-left:4px solid #185FA5;padding:16px;border-radius:8px;margin:24px 0;"><p style="margin:0;"><strong>Removed:</strong> your sign-in, compliance documents and uploaded files, hours logs, business trips, meeting minutes, mileage and vehicles, businesses and properties, and your signed records.</p><p style="margin:8px 0 0;">None of it can be recovered.</p></div><p><strong>One thing we cannot do for you:</strong> if you had a paid subscription, deleting your account does not cancel it. Only the App Store or Google Play can stop the billing, so please cancel there if you have not already.</p><p>If you did not ask for this, reply to this email right away.</p><p style="color:#6b7280;font-size:12px;margin-top:32px;">Compliance Co-Pilot</p></body></html>',
    '{user_name}'
  )
on conflict (template_key) do nothing;

-- ── Confirm ────────────────────────────────────────────────────────────────
-- Expect the seven deletion_requests columns.
select column_name, data_type, is_nullable
from information_schema.columns
where table_schema = 'public'
  and table_name = 'deletion_requests'
order by ordinal_position;

-- Expect 't' (RLS on) and 0 policies. Anything other than 0 is a security bug.
select relrowsecurity as rls_enabled,
       (select count(*) from pg_policies
         where schemaname = 'public' and tablename = 'deletion_requests') as policy_count
from pg_class
where oid = 'public.deletion_requests'::regclass;

-- Expect the widened list, including deletion_confirm + deletion_complete.
select pg_get_constraintdef(oid) as template_key_check
from pg_constraint
where conrelid = 'public.email_templates'::regclass
  and conname = 'email_templates_template_key_check';

-- Expect six rows. available_variables is printed raw rather than parsed: it
-- is TEXT here (see the note above), so jsonb_array_length() errors on it, and
-- because the whole file runs in one transaction that error would roll back
-- the table creation above along with it.
select template_key, subject, available_variables
from public.email_templates
order by template_key;
