// Manual meeting minutes — a no-AI, template-fill alternative to the Pro-only
// AI voice minutes. Available on every tier. The filled fields are dropped into
// a fixed professional template, saved to meeting_minutes (status 'complete')
// and documents (file_type 'minutes'), and can be exported as a branded PDF.

import { supabase, requireUserId } from './supabase';
import {
  buildBrandedDocHtml,
  sectionHeader,
  escapeHtml,
  shareHtmlAsPdf,
} from './pdfDocuments';

export type ManualMinutesStrategy = 'augusta_rule' | 'family_management' | 's_corp';

export const MANUAL_MINUTES_META: Record<
  ManualMinutesStrategy,
  { meetingType: string; strategyLabel: string }
> = {
  augusta_rule: {
    meetingType: 'Augusta Rule Business Meeting',
    strategyLabel: 'Augusta Rule',
  },
  family_management: {
    meetingType: 'Family Management Company Meeting',
    strategyLabel: 'Family Management Company',
  },
  s_corp: {
    meetingType: 'S-Corp Board Meeting',
    strategyLabel: 'S-Corp',
  },
};

export interface ManualMinutesInput {
  strategy: ManualMinutesStrategy;
  businessId: string | null;
  businessName: string | null;
  clientName: string | null;
  // ISO date (YYYY-MM-DD) for the meeting_minutes row.
  meetingDate: string;
  // Human-readable date for the document body (e.g. "March 4, 2026").
  meetingDateLabel: string;
  location: string;
  attendees: string;
  topicsDiscussed: string;
  decisionsMade: string;
  actionItems: string;
}

const DIVIDER = '═══════════════════════════════════════';
const SUBRULE = '─────────────────────────────────────';

const orNa = (s: string): string => (s.trim() ? s.trim() : 'N/A');

// Pure template fill — no GPT call. Produces the plain-text minutes document
// stored on both the meeting_minutes and documents rows.
export function buildManualMinutesText(input: ManualMinutesInput): string {
  const meta = MANUAL_MINUTES_META[input.strategy];
  const business =
    input.businessName?.trim() || input.clientName?.trim() || '';
  const location = orNa(input.location);
  const lines: string[] = [
    DIVIDER,
    meta.meetingType.toUpperCase(),
  ];
  if (business) lines.push(business);
  lines.push(
    `Date: ${input.meetingDateLabel}`,
    `Location: ${location}`,
    DIVIDER,
    '',
    'ATTENDEES PRESENT:',
    orNa(input.attendees),
    '',
    'MEETING CALLED TO ORDER:',
    `The meeting was called to order on ${input.meetingDateLabel} at ${location}.`,
    '',
    'TOPICS DISCUSSED:',
    orNa(input.topicsDiscussed),
    '',
    'DECISIONS MADE:',
    orNa(input.decisionsMade),
    '',
    'ACTION ITEMS:',
    orNa(input.actionItems),
    '',
    'ADJOURNMENT:',
    'There being no further business, the meeting was adjourned.',
    '',
    SUBRULE,
    `These minutes are maintained as part of the ${meta.strategyLabel} compliance records for ${business || 'the client'}.`,
    'Generated by Compliance Co-Pilot.',
    DIVIDER,
  );
  return lines.join('\n');
}

const docName = (input: ManualMinutesInput): string =>
  `${MANUAL_MINUTES_META[input.strategy].meetingType} — ${input.meetingDateLabel}`;

const attendeeCount = (attendees: string): number | null => {
  const n = attendees
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean).length;
  return n > 0 ? n : null;
};

// Persists the minutes to meeting_minutes (complete) and documents (minutes),
// mirroring the AI-minutes save path. Returns the generated document text.
export async function saveManualMinutes(
  input: ManualMinutesInput,
): Promise<{ text: string }> {
  const userId = await requireUserId();
  const meta = MANUAL_MINUTES_META[input.strategy];
  const text = buildManualMinutesText(input);

  const { error: mErr } = await supabase.from('meeting_minutes').insert({
    user_id: userId,
    business_id: input.businessId,
    meeting_type: meta.meetingType,
    location: input.location.trim() || null,
    meeting_date: input.meetingDate,
    transcript: null,
    minutes_document: text,
    attendee_count: attendeeCount(input.attendees),
    status: 'complete',
  });
  if (mErr) throw new Error(mErr.message);

  const { error: dErr } = await supabase.from('documents').insert({
    user_id: userId,
    business_id: input.businessId,
    name: docName(input),
    strategy_category: input.strategy,
    file_type: 'minutes',
    file_url: text,
  });
  if (dErr) throw new Error(dErr.message);

  return { text };
}

// Converts a multi-line field into escaped clause paragraphs (one per line).
const paraBlock = (text: string): string => {
  const trimmed = text.trim();
  if (!trimmed) return `<p class="clause">N/A</p>`;
  return trimmed
    .split(/\r?\n/)
    .map((l) => `<p class="clause">${escapeHtml(l)}</p>`)
    .join('\n');
};

// Branded PDF export (navy header + company logo), matching the existing report
// style.
export async function shareManualMinutesPdf(
  input: ManualMinutesInput,
): Promise<void> {
  const meta = MANUAL_MINUTES_META[input.strategy];
  const business =
    input.businessName?.trim() || input.clientName?.trim() || '';
  const location = orNa(input.location);
  const bodyHtml = [
    sectionHeader('Attendees Present'),
    paraBlock(input.attendees),
    sectionHeader('Meeting Called to Order'),
    `<p class="clause">The meeting was called to order on ${escapeHtml(
      input.meetingDateLabel,
    )} at ${escapeHtml(location)}.</p>`,
    sectionHeader('Topics Discussed'),
    paraBlock(input.topicsDiscussed),
    sectionHeader('Decisions Made'),
    paraBlock(input.decisionsMade),
    sectionHeader('Action Items'),
    paraBlock(input.actionItems),
    sectionHeader('Adjournment'),
    `<p class="clause">There being no further business, the meeting was adjourned.</p>`,
  ].join('\n');

  const headerLines = [
    business,
    `Date: ${input.meetingDateLabel}`,
    `Location: ${location}`,
  ].filter(Boolean);

  const html = buildBrandedDocHtml({
    title: meta.meetingType,
    headerLines,
    bodyHtml,
    footer: `These minutes are maintained as part of the ${meta.strategyLabel} compliance records${
      business ? ` for ${business}` : ''
    }. Generated by Compliance Co-Pilot.`,
  });
  await shareHtmlAsPdf(html, meta.meetingType);
}
